CREATE TABLE IF NOT EXISTS `EMPLOYEE` 
(
  `EMPLOYEEID` int(100) NOT NULL AUTO_INCREMENT,
  
`EMPLOYEENAME` varchar(30) NOT NULL,
  
`EMPLOYEEBIRTHDAY` varchar(20) NOT NULL,
   
`EMPLOYEEADDRESS` varchar(20) NOT NULL,
    
`EMPLOYEEPHONE` varchar(20) NOT NULL,
	
`EMPLOYEEMAIL` varchar(20) NOT NULL,
	
`EMPLOYEECOST` varchar(20) NOT NULL,
  
`POSITIONID` int(100) NOT NULL,
`LOGINID` int(100) NOT NULL,

  
`CREATE_USER` varchar(10) NOT NULL,
  
`CREATE_DATE` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  
`UPDATE_USER` varchar(10) NOT NULL,
  `UPDATE_DATE` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`EMPLOYEEID`)
) 
ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2 ;



CREATE TABLE IF NOT EXISTS `POSITION` 
(
  `POSITIONID` int(100) NOT NULL AUTO_INCREMENT,
  
`POSITIONCODE` varchar(30) NOT NULL,
  
`POSITIONNAME` varchar(20) NOT NULL,
   
`POSITIONDETAIL` varchar(20) NOT NULL,
     
`CREATE_USER` varchar(10) NOT NULL,
  
`CREATE_DATE` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  
`UPDATE_USER` varchar(10) NOT NULL,
  `UPDATE_DATE` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`POSITIONID`)
) 
ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2 ;