

----------------//Start TYPE
-------//Create Table TYPE
CREATE TABLE IF NOT EXISTS `TYPE` (
  `TYPEID` int(100) NOT NULL AUTO_INCREMENT,
  `TYPECODE` varchar(30) NOT NULL,
  `TYPENAME` varchar(20) NOT NULL,
  `CREATE_USER` varchar(10) NOT NULL,
  `CREATE_DATE` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `UPDATE_USER` varchar(10) NOT NULL,
  `UPDATE_DATE` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`TYPEID`),
  UNIQUE KEY `LOGIN` (`TYPECODE`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2 ;

-------//Insert Table TYPE
INSERT INTO `TYPE` (`TYPEID`, `TYPECODE`, `TYPENAME`, `CREATE_USER`, `CREATE_DATE`, `UPDATE_USER`, `UPDATE_DATE`) VALUES
(1, 'admin', 'administrator', 'admin', '2015-08-06 10:41:47.245609', 'admin', '2015-08-06 10:41:47.245609');

----------------//Start MEDICINE
-------//Create Table TYPE
CREATE TABLE IF NOT EXISTS `MEDICINE` (
  `MEDICINEID` int(100) NOT NULL AUTO_INCREMENT,
  `MEDICINENAME` varchar(30) NOT NULL,
  `MEDICINECOST` int(100) NOT NULL,
  `TYPEID` int(100) NOT NULL,
  `CREATE_USER` varchar(10) NOT NULL,
  `CREATE_DATE` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `UPDATE_USER` varchar(10) NOT NULL,
  `UPDATE_DATE` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`MEDICINEID`),
  UNIQUE KEY `MEDICINE` (`MEDICINENAME`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2 ;

-------//Insert Table LOGIN
INSERT INTO `LOGIN` (`LGID`, `LGUSERNAME`, `LGPASSWORD`, `LGROLEID`, `CREATE_USER`, `CREATE_DATE`, `UPDATE_USER`, `UPDATE_DATE`) VALUES
(1, 'admin', 'adminadmin', 1, 'admin', '2015-08-06 10:41:47.245609', 'admin', '2015-08-06 10:41:47.245609');

