CREATE TABLE IF NOT EXISTS `PATIENTTREATMENT` (
  `PATIENTTREATMENTID` int(100) NOT NULL AUTO_INCREMENT,
  `PATIENTTREATMENTDISEASENAME` varchar(30) NOT NULL,
  `PATIENTTREATMENTDATE` varchar(30) NOT NULL,
  `PATIENTTREATMENTHEARTRATE` varchar(30) NOT NULL,
  `PATIENTTREATMENTPRESSURE` varchar(30) NOT NULL,
  `PATIENTTREATMENTAGE` int(100) NOT NULL,
  `PATIENTTREATMENTWEIGHT` varchar(30) NOT NULL,
  `PATIENTTREATMENTHEIGHT` varchar(30) NOT NULL,
  `PATIENTTREATMENTSTATUS` varchar(30) NOT NULL,
  `PATIENTID` int(100) NOT NULL,
  `CREATE_USER` varchar(10) NOT NULL,
  `CREATE_DATE` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `UPDATE_USER` varchar(10) NOT NULL,
  `UPDATE_DATE` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  
  PRIMARY KEY (`PATIENTTREATMENTID`)
  
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;


CREATE TABLE IF NOT EXISTS `PATIENT` (
  `PATIENTID` int(100) NOT NULL AUTO_INCREMENT,
  `PATIENTNAME` varchar(30) NOT NULL,
  `PATIENTBIRTHDAY` varchar(30) NOT NULL,
  `PATIENTADDRESS` varchar(30) NOT NULL,
  `PATIENTPHONE` varchar(30) NOT NULL,
  `PATIENTEMAIL` varchar(30) NOT NULL,
  `PATIENTGENDER` varchar(30) NOT NULL,
  `PATIENTJOB` varchar(30) NOT NULL,
  `PATIENTBLOOODGROUP` varchar(30) NOT NULL,
  `CREATE_USER` varchar(10) NOT NULL,
  `CREATE_DATE` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `UPDATE_USER` varchar(10) NOT NULL,
  `UPDATE_DATE` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  
  PRIMARY KEY (`PATIENTID`)
  
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;


CREATE TABLE IF NOT EXISTS `ALLERGIC` (
  `ALLERGICID` int(100) NOT NULL AUTO_INCREMENT,
  `ALLERGICCODE` varchar(30) NOT NULL,
  `ALLERGICNAME` varchar(30) NOT NULL,
  `ALLERGICDETAIL` varchar(30) NOT NULL,
  `PATIENTID` int(100) NOT NULL,
  `CREATE_USER` varchar(10) NOT NULL,
  `CREATE_DATE` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `UPDATE_USER` varchar(10) NOT NULL,
  `UPDATE_DATE` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  
  PRIMARY KEY (`ALLERGICID`)
  
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
